[tools]
luau-lsp = { source = "JohnnyMorganz/luau-lsp", version = "*" }
moonwave-extractor = { source = "UpliftGames/moonwave", version = "0.3" }
rojo = { source = "rojo-rbx/rojo", version = "7" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3" }
selene = { source = "kampfkarren/selene", version = "*" }
stylua = { source = "JohnnyMorganz/StyLua", version = "*" }
wally = { source = "UpliftGames/wally", version = "0.3" }
