[tools]
darklua = { source = "seaofvoices/darklua", version = "0.13.1" }
luau-lsp = { source = "JohnnyMorganz/luau-lsp", version = "1.32.3" }
lune = { source = "lune-org/lune", version = "0.8.7" }
moonwave-extractor = { source = "UpliftGames/moonwave", version = "1.1.3" }
rojo = { source = "rojo-rbx/rojo", version = "7.4.3" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
selene = { source = "Kampfkarren/selene", version = "0.27.1" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.20.0" }
wally = { source = "UpliftGames/wally", version = "0.3.2" }
wally-package-types = { source = "JohnnyMorganz/wally-package-types", version = "1.3.2" }
