return {
	package = {
		name = "ModuleLoader",
		version = "0.11.0",
		dependencies = {
			["flipbook-batteries"] = {
				rev = "v0.12.0",
				sourceKind = "github",
				source = "https://github.com/flipbook-labs/flipbook-batteries",
			},
		},
		dev_dependencies = {
			AgentSkills = {
				rev = "v0.4.0",
				sourceKind = "github",
				source = "https://github.com/flipbook-labs/agent-skills",
			},
		},
	},
}
