[package]
name = "vocksel/module-loader"
description = "Module loader class that bypasses Roblox's require cache"
version = "0.2.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = [
    "src",
    "src/**",
    "default.project.json",
    "LICENSE",
    "README.md",
    "wally.toml",
]
