[package]
name = "vocksel/module-loader"
description = "Module loader class that bypasses Roblox's require cache"
version = "0.4.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = [
    "src",
    "src/**",
    "default.project.json",
    "LICENSE",
    "README.md",
    "wally.toml",
]

[dependencies]
GoodSignal = "stravant/goodsignal@0.1.1"
Janitor = "howmanysmall/janitor@1.13.15"
TestEZ = "roblox/testez@0.4.1"
Mock = "vocksel/mock@0.1.1"