[package]
name = "flipbook-labs/module-loader"
description = "Module loader class that bypasses Roblox's require cache"
version = "0.6.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = [
    "dist",
    "dist/**",
    "default.project.json",
    "LICENSE",
    "README.md",
    "wally.toml",
]

[dependencies]
GoodSignal = "stravant/goodsignal@0.1.1"
Janitor = "howmanysmall/janitor@1.13.15"

#[dev-dependencies]
Jest = "jsdotlua/jest@3.6.1-rc.2"
JestGlobals = "jsdotlua/jest-globals@3.6.1-rc.2"
