name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Every day at 8pm UTC (12am PST)
    - cron: "0 20 * * *"

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Foreman dependencies
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: |
          selene generate-roblox-std
          selene src/

      - name: Format
        run: stylua --check src/
