name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.1.1

      - name: Install packages
        run: lute run install

      - name: Lint
        run: lute run lint

      - name: Get model file name
        run: |
          name=$(jq -r .name default.project.json)
          sha=${GITHUB_SHA:0:7}
          echo "MODEL_FILE=$name-$sha.rbxm" >> $GITHUB_ENV

      - name: Build
        run: lute run build --channel prod --output ${{ env.MODEL_FILE }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MODEL_FILE }}
          path: ${{ env.MODEL_FILE }}

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.1.1

      - name: Setup Lute typedefs
        run: lute setup

      - name: Install packages
        run: lute run install

      - name: Run Luau analysis
        run: lute run analyze

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.1.1

      - name: Install packages
        run: lute run install

      - name: Run tests
        run: lute run test --apiKey ${{ secrets.ROBLOX_API_KEY }}
