name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v6

      - uses: flipbook-labs/changewrite@v0.5.0
        with:
          require-entry: 'true'

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - uses: CompeyDev/setup-rokit@v0.2.1
        with:
          version: v1.2.0

      - name: Install packages
        run: lute run install

      - name: Lint
        run: lute run lint

      - name: Get model file name
        run: |
          name=$(jq -r .name default.project.json)
          sha=${GITHUB_SHA:0:7}
          echo "MODEL_FILE=$name-$sha.rbxm" >> $GITHUB_ENV

      - name: Build
        run: lute run build --channel prod --output ${{ env.MODEL_FILE }}

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ env.MODEL_FILE }}
          path: ${{ env.MODEL_FILE }}

  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - uses: CompeyDev/setup-rokit@v0.2.1
        with:
          version: v1.2.0

      - name: Install packages
        run: lute run install

      - name: Run Luau analysis
        run: lute run analyze

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - uses: CompeyDev/setup-rokit@v0.2.1
        with:
          version: v1.2.0

      - name: Install packages
        run: lute run install

      - name: Load secrets from 1Password
        uses: 1Password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          ROBLOX_API_KEY: op://Flipbook/Flipbook CI (Open Cloud)/password

      - name: Run tests
        run: lute run test --apiKey "$ROBLOX_API_KEY"
