name: Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.1.1

      - uses: actions/setup-node@v3

      - name: Install Moonwave
        run: npm install -g moonwave

      - name: Extract
        run: moonwave-extractor extract src

      - name: Build
        run: moonwave build

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Use GITHUB_TOKEN to allow pushing
        run: git remote set-url origin https://github-actions[bot]:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        run: moonwave build --publish
