name: Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.1.1

      - uses: actions/setup-node@v3

      - name: Install Moonwave
        run: npm install -g moonwave

      - name: Extract
        run: moonwave-extractor extract src

      - name: Build
        run: moonwave build

      - uses: actions/upload-pages-artifact@v4
        with:
          path: build

  deploy-docs:
    # if: github.event_name != 'pull_request'
    needs: [build-docs]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
